src/Equinox.UI.Web/Controllers/CustomerController.cs
using System;
using System.Threading.Tasks;
using Equinox.Application.Interfaces;
using Equinox.Application.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetDevPack.Identity.Authorization;
using NetDevPack.Identity.Model;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Equinox.UI.Web.Controllers
{
    [Authorize]
    public class CustomerController : BaseController
    {
        private readonly ICustomerAppService _customerAppService;
        private readonly SignInManager<IdentityUser> _signInManager;

        public CustomerController(ICustomerAppService customerAppService, SignInManager<IdentityUser> signInManager)
        {
            _customerAppService = customerAppService;
            _signInManager = signInManager;
        }

        // Nova Action para o logout
        [HttpPost("customer-management/logout")]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }


        [HttpGet("customer-management/list-all")]
        public async Task<IActionResult> Index()
        {
            return View(await _customerAppService.GetAll());
        }

        [HttpGet("customer-management/customer-details/{id:guid}")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return NotFound();

            var customerViewModel = await _customerAppService.GetById(id.Value);

            if (customerViewModel == null) return NotFound();

            return View(customerViewModel);
        }

        [CustomAuthorize("Customers", "Write")]
        [HttpGet("customer-management/register-new")]
        public IActionResult Create()
        {
            return View();
        }

        [CustomAuthorize("Customers", "Write")]
        [HttpPost("customer-management/register-new")]
        public async Task<IActionResult> Create(CustomerViewModel customerViewModel)
        {
            if (!ModelState.IsValid) return View(customerViewModel);
            
            if (ResponseHasErrors(await _customerAppService.Register(customerViewModel)))
                return View(customerViewModel);

            ViewBag.Sucesso = "Customer Registered!";

            return View(customerViewModel);
        }

        [CustomAuthorize("Customers", "Write")]
        [HttpGet("customer-management/edit-customer/{id:guid}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            var customerViewModel = await _customerAppService.GetById(id.Value);

            if (customerViewModel == null) return NotFound();

            return View(customerViewModel);
        }

        [CustomAuthorize("Customers", "Write")]
        [HttpPost("customer-management/edit-customer/{id:guid}")]
        public async Task<IActionResult> Edit(CustomerViewModel customerViewModel)
        {
            if (!ModelState.IsValid) return View(customerViewModel);
            
            if (ResponseHasErrors(await _customerAppService.Update(customerViewModel)))
                return View(customerViewModel);

            ViewBag.Sucesso = "Customer Updated!";

            return View(customerViewModel);
        }

        [CustomAuthorize("Customers", "Remove")]
        [HttpGet("customer-management/remove-customer/{id:guid}")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return NotFound();

            var customerViewModel = await _customerAppService.GetById(id.Value);

            if (customerViewModel == null) return NotFound();

            return View(customerViewModel);
        }

        [CustomAuthorize("Customers", "Remove")]
        [HttpPost("customer-management/remove-customer/{id:guid}"), ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (ResponseHasErrors(await _customerAppService.Remove(id)))
                return View(await _customerAppService.GetById(id));

            ViewBag.Sucesso = "Customer Removed!";
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpGet("customer-management/customer-history/{id:guid}")]
        public async Task<JsonResult> History(Guid id)
        {
            var customerHistoryData = await _customerAppService.GetAllHistory(id);
            return Json(customerHistoryData);
        }


      
        
    }
}

src/Equinox.UI.Web/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Equinox.UI.Web.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Default");
        }
    }
}

src/Equinox.UI.Web/Views/Customer/Create.cshtml
@model Equinox.Application.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Register new Customer";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <hr />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Equinox.UI.Web/Views/Customer/Delete.cshtml
@model Equinox.Application.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Delete Customer";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Delete">
    <vc:summary />

    <h3>Are you sure you want to delete the @Model.Name?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BirthDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BirthDate)
            </dd>
        </dl>


        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

src/Equinox.UI.Web/Views/Customer/Details.cshtml
@model Equinox.Application.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Customer Details";
}

<h2>@ViewData["Title"]</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> 
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

src/Equinox.UI.Web/Views/Customer/Edit.cshtml
@model Equinox.Application.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Edit Customer";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <hr />

        <input type="hidden" asp-for="Id" />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Equinox.UI.Web/Views/Customer/Index.cshtml
@model IEnumerable<Equinox.Application.ViewModels.CustomerViewModel>

@{
    ViewData["Title"] = "Customer Management";
}

<style>
    .modal-lg {
        max-width: 80%;
    }
</style>

<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />

<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="fas fa-plus"></span> Register New
                </a>
            </div>
        </div>
    </div>
</div>
<br />

<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                        <span class="fas fa-edit"></span>
                    </a>
                        
                    <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                        <span class="fas fa-search"></span>
                    </a>
                        
                    <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                        <span class="fas fa-trash-alt"></span>
                    </a>
                    
                    <button type="button" class="btn btn-info viewbutton" title="History" data-id="@item.Id" data-toggle="modal" data-target="#customerHistory">
                        <span class="fas fa-clock"></span>
                    </button>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

@*<div class="modal fade" id="customerHistory" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Customer Data History</h4>
            </div>
            <div class="modal-body">
                <p id="customerHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>*@


<div class="modal fade" id="customerHistory" tabindex="-1" role="dialog" aria-labelledby="historyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="historyModalLabel">Customer Data History</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="customerHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $(".viewbutton").on("click", function() {
            var customerId = $(this).data('id');
            $.ajax({
                url: "https://localhost:44314/customer-management/customer-history/" + customerId,
                //url: "http://equinoxproject.azurewebsites.net/customer-management/customer-history/" + customerId,
                cache: false
            }).done(function(data) {
                var formatHtml = "<table class='table table-striped'>";
                formatHtml += "<thead><th>Action</th><th>When</th><th>Id</th><th>Name</th><th>E-mail</th><th>Birth Date</th><th>By User</th></thead>";

                for (var i = 0; i < data.length; i++) {
                    var change = data[i];
                    formatHtml += "<tr>";
                    formatHtml += "<td>" + change.action + "</td>";
                    formatHtml += "<td>" + change.timestamp + "</td>";
                    formatHtml += "<td>" + change.id + "</td>";
                    formatHtml += "<td>" + change.name + "</td>";
                    formatHtml += "<td>" + change.email + "</td>";
                    formatHtml += "<td>" + change.birthDate + "</td>";
                    formatHtml += "<td>" + change.who + "</td>";
                    formatHtml += "</tr>";
                }
                formatHtml += "</table>";
                $("#customerHistoryData").html(formatHtml);
            });
        });
</script>
}